ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'USER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EDITOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'OWNER';

UPDATE "User" SET role = 'USER' WHERE role = 'STONEHOLDER';

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';