packages:
  - "."
overrides:
  postcss: '8.5.28'
  browserslist: '4.28.9'
  baseline-browser-mapping: '2.11.23'
  deepmerge-ts: '8.0.2'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@babel/core@7.29.1'
  - dompurify@3.3.4
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - prisma
  - sharp
